[general]
import = [
    "~/my-config/alacritty/themes/zenwritten_light.toml"
]
live_config_reload = true
[env]
term = "xterm-256color"
[window]
decorations = "None"
startup_mode = "Fullscreen"
[font]
size = 20
normal = { family = "JetBrainsMono NF" }
